### ISSUE TITLE
Makefile doesn't work with tree-sitter 0.22

### ISSUE THREAD

**Issue by mavit** [camdencheek/tree-sitter-dockerfile#48]
With recent versions of tree-sitter, `make` ends with the following error:

```
src/parser.c:1:10: fatal error: tree_sitter/parser.h: No such file or directory
    1 | #include <tree_sitter/parser.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/parser.o] Error 1
```

This appears to do the trick:

```bash
rm Makefile
tree-sitter generate
sed -i 's/^VERSION := 0\.0\.1$/VERSION := 0.1.2/' Makefile
```

**Comment by camdencheek** [comment]
Fixed! Thanks for the report.

**Comment by mavit** [comment]
Thanks, but now it fails with:

```console
install: cannot stat 'bindings/c/tree-sitter-dockerfile.h': No such file or directory
make: *** [Makefile:91: install] Error 1
```

This file is created by `tree-sitter generate`, but this is obscured by the following `.gitignore` rule:

```gitignore
/bindings/c/*.h
```
